name: Run Matches
on: [pull_request]
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  test_private_action_job:
    name: Run Matches
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: List Files
        run: ls
      # run python/java to play against precompiled programs - pipe results to file
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run Match
        run: sudo python run_matches.py
      # upload match files as artifact
      - name: Archive Match Files
        uses: actions/upload-artifact@v2
        with:
          name: matches
          path: matches
          retention-days: 90
      # upload summary as artifact
      - name: Archive Summary
        uses: actions/upload-artifact@v2
        with:
          name: matches-summary
          path: matches-summary.txt
          retention-days: 90
      # Post results on github comments - https://github.com/marketplace/actions/create-or-update-comment
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Build Output
      - name: Generate Comment
        id: get-comment-body
        run: |
          body="$(cat matches-summary.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build Output (updated for ${{ github.event.pull_request.head.sha }})
            Workflow Run (#${{ github.run_number }}): ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ${{ steps.get-comment-body.outputs.body }}
          edit-mode: replace